<a href="https://colab.research.google.com/github/dannywinter/2025_ML_hws/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def softmax_0(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size


In [4]:
# 五筆輸入資料 (X) 與真實標籤 (Y)
X = np.array([
    [0.5, 0.8, 0.2, 0.9, 0.3, 0.7],
    [0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3, 0.2, 0.1],
    [0.9, 0.8, 0.7, 0.6, 0.5, 0.4],
    [0.3, 0.2, 0.1, 0.6, 0.5, 0.4]
])  # shape = (5, 6)

Y = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0],
    [1, 0, 0],
    [0, 1, 0]
])  # shape = (5, 3)

print("X shape:", X.shape)
print("Y shape:", Y.shape)


X shape: (5, 6)
Y shape: (5, 3)


In [5]:
# Layer 1: 6 → 5
W1 = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2, 0.1],
    [0.6, 0.7, 0.8, 0.9, 0.1],
    [0.1, 0.3, 0.5, 0.7, 0.9],
    [0.9, 0.8, 0.7, 0.6, 0.5],
    [0.4, 0.3, 0.2, 0.1, 0.0]
])  # (6,5)
b1 = np.array([0.1, 0.1, 0.1, 0.1, 0.1])

# Layer 2: 5 → 4
W2 = np.array([
    [0.2, 0.1, 0.4, 0.3],
    [0.5, 0.6, 0.7, 0.8],
    [0.1, 0.3, 0.5, 0.7],
    [0.9, 0.7, 0.5, 0.3],
    [0.3, 0.2, 0.1, 0.4]
])  # (5,4)
b2 = np.array([0.2, 0.2, 0.2, 0.2])

# Layer 3: 4 → 4
W3 = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.4, 0.3, 0.2],
    [0.6, 0.7, 0.8, 0.9],
    [0.9, 0.8, 0.7, 0.6]
])  # (4,4)
b3 = np.array([0.3, 0.3, 0.3, 0.3])

# Layer 4: 4 → 3
W4 = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.3, 0.2],
    [0.5, 0.6, 0.7],
    [0.8, 0.9, 0.1]
])  # (4,3)
b4 = np.array([0.1, 0.1, 0.1])


In [6]:
# Layer 1
z1 = np.dot(X, W1) + b1  # shape: (5, 5)
h1 = relu(z1)

# Layer 2
z2 = np.dot(h1, W2) + b2  # shape: (5, 4)
h2 = relu(z2)

# Layer 3
z3 = np.dot(h2, W3) + b3  # shape: (5, 4)
h3 = sigmoid(z3)

# Layer 4
z4 = np.dot(h3, W4) + b4  # shape: (5, 3)
y_hat = softmax_0(z4)

# 顯示結果與形狀
print("z1:", z1.shape, "\nh1:", h1.shape)
print("z2:", z2.shape, "\nh2:", h2.shape)
print("z3:", z3.shape, "\nh3:", h3.shape)
print("z4:", z4.shape, "\ny_hat:", y_hat.shape)
print("y_hat:\n", y_hat)


z1: (5, 5) 
h1: (5, 5)
z2: (5, 4) 
h2: (5, 4)
z3: (5, 4) 
h3: (5, 4)
z4: (5, 3) 
y_hat: (5, 3)
y_hat:
 [[0.07094194 0.0866378  0.04304261]
 [0.07061148 0.08618957 0.042899  ]
 [0.07047699 0.08600721 0.04284047]
 [0.07100972 0.08672977 0.0430718 ]
 [0.07055451 0.08611234 0.04287479]]


In [7]:
loss = cross_entropy_error(y_hat, Y)
print("平均交叉熵誤差 =", loss)


平均交叉熵誤差 = 2.6692969934825532
